name: gitlab-runner

services:
  runner:
    container_name: runner
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    volumes:
      - ./config:/etc/gitlab-runner:z
      - /var/run/docker.sock:/var/run/docker.sock
